services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./sites-available:/etc/nginx/sites-available
      - ./logs:/var/log/nginx
      - ./www:/var/www
    ports:
      - "80:80" #http
      - "443:443" #https
